# Configuración básica
listen=YES
local_enable=YES
write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# IMPORTANTE: Ejecutar en primer plano para que Docker no mate el contenedor
background=NO

# Seguridad básica (chroot para que el usuario no salga de su carpeta)
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO

# Configuración de RED (Crucial para Docker)
pasv_enable=YES
pasv_addr_resolve=NO
# Si estás en local, usa tu IP o localhost. 
# Si falla, a veces se usa la IP de la máquina host, pero 0.0.0.0 suele funcionar en bridge.
pasv_address=127.0.0.1
pasv_min_port=21100
pasv_max_port=21110

# Logs a stdout (para verlos con 'docker logs')
xferlog_std_format=NO
log_ftp_protocol=YES
